name: Post deploy audit
on:
  push:
    branches:
      - master
jobs:
  perf:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 5m minutes
        run: sleep 300
      - uses: actions/checkout@master
      - run: mkdir /tmp/artifacts
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          outputDirectory: /tmp/artifacts
          urls: 'https://zurda.github.io/portfolio'
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: /tmp/artifacts
